name: "SF JWT Authenticate"

description: "Authenticates to SF Environment using JWT"

runs:
  using: "composite"
  steps:
      - name: Decode JWT Key File
        run: echo "${{ secrets.SF_JWT_KEY }}" | base64 --decode > .github/keys/server.key
      
      - name: Authenticate to Salesforce using JWT
        run: |
          sf org login jwt \
            --client-id ${{ secrets.CLIENT_ID }} \
            --jwt-key-file .github/keys/server.key \
            --username ${{ secrets.DEPLOY_USER }} \
            --instance-url ${{ vars.SF_INSTANCE_URL }}
      - name: Clean up private key
        if: always() 
        run: |
          rm -f .github/keys/server.key
          echo "Private key deleted successfully."
