name: "SF Map Auth Secret"

description: "Logs out of the SF Org"
inputs:
  SF_AUTH:
    required: true
    description: "YML with map of SF Orgs and connection details"
  SF_INSTANCE_KEY:
    required: true
    description: "the target SF Org URL as noted in Setup > My Domain > My Domain Details > My Domain Name"
outputs:
  SF_USERNAME:
    description: "SF Username to use for authentication."
    value: ${{ steps.set-outputs.outputs.SF_USERNAME }}
  SF_URL:
    description: "SF URL to use for authentication."
    value: ${{ steps.set-outputs.outputs.SF_URL }}
  SF_CLIENT_ID:
    description: "SF CLIENT ID to use for authentication."
    value: ${{ steps.set-outputs.outputs.SF_CLIENT_ID }}
  IS_JWT:
    description: "Indecates if the auth values are for JWT auth method.  returns true or false"
    value: ${{ steps.set-outputs.outputs.IS_JWT }}
runs:
  using: "composite"
  steps:
    - name: Extract `SF_USERNAME` and `SF_URL`  and `SF_CLIENT_ID` from SF_AUTH Secret
      id: set-outputs
      run: |
        
          echo "SF_USERNAME=$(echo $SF_AUTH | yq eval .${SF_INSTANCE_KEY}.username -)" >> "$GITHUB_OUTPUT"
          echo "SF_URL=$(echo $SF_AUTH | yq eval .${SF_INSTANCE_KEY}.url -)" >> "$GITHUB_OUTPUT"
          echo "SF_CLIENT_ID=$(echo $SF_AUTH | yq eval .${SF_INSTANCE_KEY}.client_id -)" >> "$GITHUB_OUTPUT"
         
          if [ -z "$SF_CLIENT_ID" ]; then
            echo "IS_JWT=true" >> "$GITHUB_OUTPUT"
          else
            echo "IS_JWT=false" >> "$GITHUB_OUTPUT"
          fi
      shell: bash
