name: SF CLI JWT Login

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sf-cli-login:
    runs-on: ubuntu-latest
    environment: Prod  # Use the "Prod" environment to fetch secrets
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      - name: Verify SF CLI installation
        run: sf --version

      - name: Decode JWT Key File
        run: echo "${{ secrets.SF_JWT_KEY }}" | base64 --decode > .github/keys/server.key
      
      - name: Authenticate to Salesforce using JWT
        run: |
          sf org login jwt \
            --client-id ${{ secrets.CLIENT_ID }} \
            --jwt-key-file .github/keys/server.key \
            --username ${{ secrets.DEPLOY_USER }} \
            --instance-url ${{ vars.SF_INSTANCE_URL }}
      - name: Clean up private key
        if: always() 
        run: |
          rm -f .github/keys/server.key
          echo "Private key deleted successfully."
