name: SF CLI Run Anonymous Script

on:
  workflow_dispatch:
    inputs:
      target_script:
        description: 'the script to run from ./scripts dir'
        required: true
        type: string
      arg1:
        description: 'First argument'
        required: false
        type: string
      arg2:
        description: 'Second argument'
        required: false
        type: string
      SF_INSTANCE_KEY:
        description: 'the target SF Org URL as noted in Setup > My Domain > My Domain Details > My Domain Name'
        required: true
        type: string

jobs:
  sf-cli-prepare-runner:
    runs-on: ubuntu-latest
    environment: Prod  # Use the "Prod" environment to fetch secrets
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Var check
        run: |
          echo "SF_INSTANCE_KEY=$SF_INSTANCE_KEY"
          echo "$SF_AUTH"
          
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install yq
        run: |
            sudo apt update && sudo apt install -y yq

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      - name: Verify SF CLI installation
        run: sf --version

      - name: Get Authentication Values from SF_AUTH secret
        id: sf_auth
        uses: ./.github/actions/SF_Map_Auth_Secret
        with:
          SF_AUTH: ${{ secrets.SF_AUTH }}
          SF_INSTANCE_KEY: ${{ inputs.SF_INSTANCE_KEY }}

      - name: Attempt JWT Authenticate
        if: steps.sf_auth.outputs.IS_JWT == 'true'
        id: jwt_auth
        continue-on-error: true
        uses: ./.github/actions/SF_JWT_Authenticate
        with:
          CLIENT_ID: ${{ steps.sf_auth.outputs.SF_CLIENT_ID }}
          DEPLOY_USER: ${{ steps.sf_auth.outputs.SF_USERNAME }}
          SF_INSTANCE_URL: ${{ steps.sf_auth.outputs.SF_URL }}
          SF_JWT_KEY: ${{secrets.SF_JWT_KEY}}

      - name: Attempt Device Authenticate
        if: steps.jwt_auth.outcome == 'failure'
        uses: ./.github/actions/SF_Device_Authenticate
        with:
          DEPLOY_USER: ${{ steps.sf_auth.outputs.SF_USERNAME }}
          SF_INSTANCE_URL: ${{ steps.sf_auth.outputs.SF_URL }}




      - name: Replace arg placeholders in ${{ inputs.target_script }} 
        run: |
         cp ./scripts/${{ inputs.target_script }} tmp_script.apex
         sed -i "s/#ARG1#/${{ inputs.arg1 }}/g" tmp_script.apex
         sed -i "s/#ARG2#/${{ inputs.arg2 }}/g" tmp_script.apex

      - name: Run modified ${{ inputs.target_script }} script
        run: sf apex run --target-org ${{ secrets.DEPLOY_USER }} --file tmp_script.apex

      - name: Run SF Org Logout
        uses: ./.github/actions/SF_Logout
        with:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}