name: SF CLI Run Anonymous Script

on:
  workflow_dispatch:
    inputs:
      target_script:
        description: 'the script to run from ./scripts dir'
        required: true
        type: string
      arg1:
        description: 'First argument'
        required: false
        type: string
      arg2:
        description: 'Second argument'
        required: false
        type: string
      SF_INSTANCE_URL:
        description: 'the target SF Org URL as noted in Setup > My Domain > My Domain Details > Current My Domain URL'
        required: true
        type: string

jobs:
  sf-cli-prepare-runner:
    runs-on: ubuntu-latest
    environment: Prod  # Use the "Prod" environment to fetch secrets
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      - name: Verify SF CLI installation
        run: sf --version

      - name: Attempt JWT Authenticate
        id: jwt_auth
        continue-on-error: true
        uses: ./.github/actions/SF_JWT_Authenticate
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SF_INSTANCE_URL: ${{ github.event.inputs.SF_INSTANCE_URL }}
          SF_JWT_KEY: ${{secrets.SF_JWT_KEY}}

      - name: Attempt Device Authenticate
        if: steps.jwt_auth.outcome == 'failure'
        uses: ./.github/actions/SF_Device_Authenticate
        with:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SF_INSTANCE_URL: ${{ vars.SF_INSTANCE_URL }}




      - name: Replace arg placeholders in ${{ github.event.inputs.target_script }} 
        run: |
         cp ./scripts/${{ github.event.inputs.target_script }} tmp_script.apex
         sed -i "s/#ARG1#/${{ github.event.inputs.arg1 }}/g" tmp_script.apex
         sed -i "s/#ARG2#/${{ github.event.inputs.arg2 }}/g" tmp_script.apex

      - name: Run modified ${{ github.event.inputs.target_script }} script
        run: sf apex run --target-org ${{ secrets.DEPLOY_USER }} --file tmp_script.apex

      - name: Run SF Org Logout
        uses: ./.github/actions/SF_Logout
        with:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}